repos:
- repo: https://gitlab.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies: [
      "flake8-quotes==3.3.1",
    ]

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    exclude: data/
    args: [
      "*.py *.rst *.md",
    ]

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    exclude: tbb/properties/telemac/serafin.py|tbb/auto_load.py|tests/|data/
    args: [
      "-e"
    ]